routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');


#Route::get('/agenda', 'AgendaController@index')->name('agenda.index');

Route::resource('agenda', 'AgendaController');

app/Agenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    protected $table = "agendas";
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\Agenda;
use Illuminate\Http\Request;

class AgendaController extends Controller
{
    /**
     * index - exibe uma lista dos registros da tabela
     * create - exibe um form para cadastrar dados
     * store - recebe os dados do form (create) e envia para o Model
     *         gravar na tabela (operação de inserção)
     * edit - exibe um form para alterar dados de um determinado
     *        registro lido.
     * update - recebe os dados do form (edit) e envia para o Model
     *          atualizar na tabela (operação de update)
     * show - exibe em detalhes os dados de um determinado registro
     * destroy - deleta um determinado registro
     */





    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contatos = Agenda::all();
        return view('agenda.index', compact('contatos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        Agenda::create($request->all());  
    
        return view('agenda.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function show(Agenda $agenda)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function edit(Agenda $agenda)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agenda $agenda)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agenda $agenda)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/agenda/create.blade.php
@extends('adminlte::page')

@section('title', 'AgendaL6')

@section('content_header')
<h1>Criação de um novo Contato</h1>
@stop

@section('content')
<form action="{{ route('agenda.store') }}" method="POST">
    {{csrf_field()}}
    <div class="panel panel-default">
        <div class="panel-heading">
            Cadastro de novos contatos
        </div>

        <div class="panel-body">
            <div class="form-group">
                <label for="nome">Nome do Contato</label>
                <input type="text" id="nome" name="nome" class="form-control">
            </div>

            <div class="form-group">
                <label for="fone_res">Telefone Residencial</label>
                <input type="text" id="fone_res" name="fone_res" class="form-control">
            </div>

            <div class="form-group">
                <label for="fone_cel">Telefone Celular</label>
                <input type="text" id="fone_cel" name="fone_cel" class="form-control">
            </div>

            <div class="form-group">
                <label for="dt_nasc">Data de Nascimento</label>
                <input type="date" id="dt_nasc" name="dt_nasc" class="form-control">
            </div>

        <div class="form-group">
                <label for="facebook">facebook</label>
                <input type="text" id="facebook" name="facebook" class="form-control">
            </div>

          <div class="form-group">
                <label for="instagram">instagram</label>
                <input type="text" id="instagram" name="instagram" class="form-control">
    
            </div>
                    
            <div class="form-group">
                <label for="twitter">twitter</label>
                <input type="text" id="twitter" name="twitter" class="form-control">
    
            </div>


        </div>

        <div class="panel-footer">
        <a href= "{{ route('agenda.index')}}" class="btn btn-defalt">
        <i class= "fas fa-reply"></i> voltar
        </a>

        <buttun type= "submit" class= "btn btn-sucess">
        <i class= "fas fa-save"><</i> Gravar
                </buttun>

        </div>
    </div>

</form>
@stop

@section('css')
@stop

@section('js')
@stop

resources/views/agenda/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Dashboard</h1>
@stop

@section('content')
<p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop

resources/views/agenda/index.blade.php
@extends('adminlte::page')

@section('title', 'Agenda')

@section('content_header')
<h1><i class="fas fa-fx fa-bars"></i> Lista de Agendas</h1>
@stop

@section('content')
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        Relação dos contatos da agenda
        <div class="pull-right">
            <a href="{{ route('agenda.index') }}" class="btn btn-primary btn-sm"><i class="fas fa-fx fa-sync-alt"></i> Atualizar a tela</a>
            <a href="{{ route('agenda.create') }}" class="btn btn-success btn-sm"><i class="fas fa-fx fa-plus"></i> Adicionar novo contato</a>
        </div>
    </div>

    <div class="panel-body">
        <table id="tabela" class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Celular</th>
                    <th>Email</th>
                    <th>Açoes</th>
                </tr>
            </thead>

            <tbody>
                @foreach($contatos as $contato)
                <tr>
                    <td>{{ $contato->id }}</td>
                    <td>{{ $contato->nome}}</td>
                    <td>{{ $contato->fone_cel}}</td>
                    <td>{{ $contato->email }}</td>
                    <td>acoes</td>
                </tr>
                @endforeach
            </tbody>
        </table>







    </div>
</div>
@stop

@section('css')

@stop

@section('js')
<script>
$(document).ready( function () {
    $('#tabela').DataTable();
} );
</script>
@stop

resources/views/agenda/show.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Dashboard</h1>
@stop

@section('content')
<p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    console.log('Hi!');
</script>
@stop

resources/views/home.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>You are logged in!</p>
@stop